######### Basic Settings #########
basic:
    device: '3'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: ar
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune_il
    method_type: multi_steps
    incre_type: til
    # eval_metric Choises: acc, recall
    eval_metric: acc

    apply_nme: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 1
    increment: 1

    logger_type: tensorboard

    # save_pred_record: true
    note: test
    # test_epoch: 10
    use_valid: True
######### Method's Hyperparameters #########
special:
    incre_type: cil

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    ar: 
        resnet18:
            img_size: 224

            epochs: 100 # 340
            batch_size: 128
            num_workers: 8

            opt_type: adam
            lrate: 0.0001
            weight_decay: 0.0
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [60,80]
            lrate_decay: 0.99
            
        mobilenet_v2:
            img_size: 224

            epochs: 100 # 340
            batch_size: 128
            num_workers: 8

            opt_type: adam
            lrate: 0.0001
            weight_decay: 0.0
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [60,80]
            lrate_decay: 0.99
            