######### Basic Settings #########
basic:
    device: '6'
    seed: [1993]

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: true

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, recall
    eval_metric: mcr

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    freeze_fe: false
    save_models: false # if true, programm will save model's weights during incremental train
    use_valid: True
    note: fine_tune_pretrain

######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin8:        
        resnet18:
            img_size: 224

            epochs: 2 # 340
            batch_size: 128
            num_workers: 8

            opt_type: adam
            lrate: 0.0001
            weight_decay: 0.0
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [60,80]
            lrate_decay: 0.99
            
        resnet32:
            epochs: 200 #80
            batch_size: 128
            num_workers: 8

            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9        
    
            scheduler: multi_step
            milestones: [60,120,160]
            lrate_decay: 0.1
