######### Basic Settings #########
basic:
    device: '5'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: coda_prompt
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: vit_base_patch16_224 # not used
    pretrained: true # not used
    freeze_fe: true
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 1
    increment: 1
    use_valid: True
    
    note: test

######### Method's Hyperparameters #########
special:
    incre_type: til
    prompt_pool: 100
    prompt_length: 8
    ortho_weight: 0.001

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        vit_base_patch16_224:
            img_size: 224

            epochs: 20 #20
            batch_size: 128 # 128
            num_workers: 8            

            opt_type: adam
            lrate: 0.001
            scheduler: cos
    skin8: 
        vit_base_patch16_224:
            img_size: 224
            epochs: 50 #20
            batch_size: 128 # 128
            num_workers: 8            

            opt_type: adam
            lrate: 0.001
            scheduler: cos
            
